"use strict";

var BG_TASK = {
	LOAD: 1,
	SAVE_CONFIG: 2,
	SAVE_EMOTES: 3,
	RESET_CONFIG: 4,
	RESET_EMOTES: 5,
	OPEN_OPTIONS: 6,
	UPDATE_EMOTES: 7,
	UPDATE_LIST_ORDER: 8,
	UPDATE_LIST_NAME: 9,
	UPDATE_LIST_DELETE: 10,
	UPDATE_CSS: 11
};